### ISSUE TITLE
Fastq files of R1 have different lengths

### ISSUE THREAD

**Issue by yang-qingxin** [FHentzschel/MalariaHostRBCAtlas#2]
When I run Cellranger Cout with fastq files, the software shows
![image](https://user-images.githubusercontent.com/71535886/182303700-947c576e-dbe2-40fe-914a-b54e5e466c01.png)
. Can you share the parameters you use CellRanger, thank you。

**Comment by FHentzschel** [comment]
Dear yang-qingxin, 

we have been using an older version of CellRanger which didn't have this issue. You should be able to use the --r1-lenght argument setting it to 26. That should work. 

Alternatively, you can directly work with the read matrix that we uploaded for each of the nine samples here in the "Raw Data" folder. 

Let me know if you have further issues.

**Comment by yang-qingxin** [comment]
Dear FHentzschel,
It was very helpful.
Thank you very much!

**Comment by yang-qingxin** [comment]
Thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FHentzschel/MalariaHostRBCAtlas"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月3日(星期三) 下午5:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FHentzschel/MalariaHostRBCAtlas] Fastq files of R1 have different lengths (Issue #2)





 
Dear yang-qingxin,
 
we have been using an older version of CellRanger which didn't have this issue. You should be able to use the --r1-lenght argument setting it to 26. That should work.
 
Alternatively, you can directly work with the read matrix that we uploaded for each of the nine samples here in the "Raw Data" folder.
 
Let me know if you have further issues.
